### ISSUE TITLE
undefined symbol error on Google Colab

### ISSUE THREAD

**Issue by oscarqht** [camenduru/TripoSR-jupyter#3]
Hi @camenduru , thanks for the notebook! However I'm having the following error when running on Google Colab, would be great if you can take a look when you have time. Thanks :)

```
Traceback (most recent call last):
  File "/content/TripoSR-hf/app.py", line 13, in <module>
    from tsr.system import TSR
  File "/content/TripoSR-hf/tsr/system.py", line 16, in <module>
    from .models.isosurface import MarchingCubeHelper
  File "/content/TripoSR-hf/tsr/models/isosurface.py", line 6, in <module>
    from torchmcubes import marching_cubes
  File "/usr/local/lib/python3.10/dist-packages/torchmcubes/__init__.py", line 2, in <module>
    import torchmcubes_module as mc
ImportError: /usr/local/lib/python3.10/dist-packages/torchmcubes_module.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
```

**Comment by mcanet** [comment]
yes same error to me
